language: crystal

jobs:
  include:
    - stage: build
      script: crystal build --release src/pizza-server.cr
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: berlin-pizza
        api_key: $HEROKU_AUTH_TOKEN
        on:
          branch: master
    - stage: npm publish
      script: skip
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $EMAIL
        on:
          branch: master
          tags: true
